name: tsg_env
channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - numpy
  - scipy
  - xarray
  - pandas
  - dask
  - numba
  - matplotlib
  - seaborn
  - graphviz
  - jupyterlab
  - gsw
  - pip
  - netcdf
  - cartopy
  - pip:
    - graphviz
